kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: production
  name: cassandra-vc-data
spec:
  storageClassName: generic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
