config1:
  kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: pv0001
    labels:
      type: local
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: '/somepath/data01'
# ------------------
config2:
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: myclaim
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
# -------------------
cofig3:
  kind: Pod
  apiVersion: v1
  metadata:
    name: mypod
  spec:
    containers:
      - name: myfrontend
        image: gcr.io/google_containers/echoserver:1.4
        ports:
          - containerPort: 8080
            protocol: TCP
        volumeMounts:
          - mountPath: '/var/www/html'
            name: mypd
    volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: myclaim
